import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const API='http://localhost:8000';
function App(){
 const [files,setFiles]=useState([]),[question,setQuestion]=useState(''),[answer,setAnswer]=useState(''),[sources,setSources]=useState([]),[status,setStatus]=useState('System ready.'),[busy,setBusy]=useState(false);
 async function upload(){if(!files.length)return;setBusy(true);setStatus('Indexing documents...');const fd=new FormData();files.forEach(f=>fd.append('files',f));try{const r=await fetch(API+'/upload',{method:'POST',body:fd});const d=await r.json();setStatus(`Added ${d.added.length} file(s), skipped ${d.skipped.length}, errors ${d.errors.length}.`)}catch(e){setStatus('Backend unavailable. Start FastAPI first.')}finally{setBusy(false)}}
 async function ask(){if(!question.trim())return;setBusy(true);setStatus('Searching knowledge base...');try{const r=await fetch(API+'/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question})});const d=await r.json();setAnswer(d.answer);setSources(d.sources||[]);setStatus('Response generated.')}catch(e){setStatus('Could not reach NEXUS backend.')}finally{setBusy(false)}}
 return <div className="app"><header><div className="brand"><span className="orb">✦</span><div><h1>NEXUS</h1><p>Neural Extraction & Unified Search</p></div></div><span className="live">● LOCAL SYSTEM</span></header><main><section className="hero"><p className="eyebrow">DOCUMENT INTELLIGENCE / RAG CORE</p><h2>Your knowledge.<br/><span>Connected.</span></h2><p className="sub">Upload PDFs, search across documents, and receive grounded answers with page-level sources.</p></section><section className="panel"><div className="panel-title"><h3>01 / INGEST DOCUMENTS</h3><span>MAX 50 PDFs</span></div><label className="drop"><input type="file" accept="application/pdf" multiple onChange={e=>setFiles([...e.target.files].slice(0,50))}/><strong>Drop PDFs here or choose files</strong><small>{files.length?`${files.length} file(s) selected`:'PDF text extraction · duplicate detection'}</small></label><button onClick={upload} disabled={busy||!files.length}>INITIALIZE INDEXING ↗</button></section><section className="panel"><div className="panel-title"><h3>02 / QUERY NEXUS</h3><span>TOP-K SEMANTIC SEARCH</span></div><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask anything about your uploaded documents..."/><button onClick={ask} disabled={busy||!question.trim()}>RUN QUERY ↗</button>{answer&&<div className="answer"><h4>RESPONSE</h4><p>{answer}</p>{sources.length>0&&<><h4>SOURCES</h4><ul>{sources.map((s,i)=><li key={i}>{s.filename} · page {s.page} · relevance {s.score}</li>)}</ul></>}</div>}</section><div className="status">{busy?'◌ ': '✓ '}{status}</div></main></div>
}
createRoot(document.getElementById('root')).render(<App/>);
